version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: inscripciones
    #restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
      # - 80:80
    volumes: 
      - ./:/app

  db:
    image: mariadb
    container_name: inscripciones-db
    #restart: always
    environment:
      MYSQL_DATABASE: inscripciones
      MYSQL_USER: inscripcionesuser
      MYSQL_PASSWORD: "admin1234"
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3310:3306
 
volumes:
  db:    


