# Generated by Django 4.1.4 on 2023-05-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('usuarios', '0003_cliente_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entregada', models.BooleanField(default=False)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carrito.carrito', verbose_name='Carrito')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
