# Generated by Django 4.1.4 on 2023-05-08 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0009_resena'),
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='articulo1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo1_v', to='articulos.articulo', verbose_name='articulo1_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo10',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo10_v', to='articulos.articulo', verbose_name='articulo10_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo2_v', to='articulos.articulo', verbose_name='articulo2_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo3_v', to='articulos.articulo', verbose_name='articulo3_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo4_v', to='articulos.articulo', verbose_name='articulo4_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo5_v', to='articulos.articulo', verbose_name='articulo5_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo6',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo6_v', to='articulos.articulo', verbose_name='articulo6_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo7',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo7_v', to='articulos.articulo', verbose_name='articulo7_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo8',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo8_v', to='articulos.articulo', verbose_name='articulo8_v'),
        ),
        migrations.AddField(
            model_name='venta',
            name='articulo9',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo9_v', to='articulos.articulo', verbose_name='articulo9_v'),
        ),
    ]
