# Generated by Django 4.1.4 on 2023-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_venta_articulo1_venta_articulo10_venta_articulo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='articulo1',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo10',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo2',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo3',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo4',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo5',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo6',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo7',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo8',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='articulo9',
        ),
        migrations.AddField(
            model_name='venta',
            name='detalle',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
