# Generated by Django 4.1.4 on 2023-05-18 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0010_alter_articulo_nombre'),
        ('reportes', '0003_remove_venta_articulo1_remove_venta_articulo10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='detalle',
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articulos.articulo', verbose_name='detalleArticulo')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.venta', verbose_name='Detalle')),
            ],
        ),
    ]
