# Generated by Django 4.1.6 on 2023-05-05 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_alter_articulo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to='articulos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'], code='formato_invalido', message='Sólo se permite formato PNG, JPEG, JPG.')], verbose_name='Foto del Artículo'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='talla',
            field=models.CharField(choices=[('', 'Unitalla'), ('CH', 'Chica'), ('M', 'Mediana'), ('G', 'Grande'), ('XL', 'Extra Grande')], max_length=8),
        ),
    ]
