# Generated by Django 4.1.6 on 2023-05-05 23:14

import articulos.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0003_alter_articulo_imagen_alter_articulo_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(upload_to=articulos.validators.directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'], code='formato_invalido', message='Sólo se permite formato PNG, JPEG, JPG.')], verbose_name='Foto del Artículo'),
        ),
    ]
