# Generated by Django 4.1.6 on 2023-05-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0004_alter_articulo_descripcion_alter_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.TextField(blank=True, default='Sin descripcion', max_length=250),
            preserve_default=False,
        ),
    ]
