# Generated by Django 4.1.6 on 2023-05-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0007_alter_articulo_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articulo',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='articulo',
            name='talla',
            field=models.CharField(choices=[('UNI', 'Unitalla'), ('CH', 'Chica'), ('M', 'Mediana'), ('G', 'Grande'), ('XL', 'Extra Grande')], max_length=8),
        ),
    ]
