# Generated by Django 4.1.6 on 2023-06-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0012_rename_id_articulo_imagenesarticulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagenesarticulo',
            name='nombre',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
