# Generated by Django 4.1.6 on 2023-06-06 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0013_imagenesarticulo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesarticulo',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='articulos.articulo'),
        ),
    ]
