# Generated by Django 4.1.6 on 2023-06-07 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0012_articulo_imagen2_articulo_imagen3_articulo_imagen4_and_more'),
        ('articulos', '0014_alter_imagenesarticulo_articulo'),
    ]

    operations = [
    ]
