# Generated by Django 4.1.4 on 2023-05-07 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulos', '0009_resena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('articulo1', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo1', to='articulos.articulo', verbose_name='articulo1')),
                ('articulo10', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo10', to='articulos.articulo', verbose_name='articulo10')),
                ('articulo2', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo2', to='articulos.articulo', verbose_name='articulo2')),
                ('articulo3', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo3', to='articulos.articulo', verbose_name='articulo3')),
                ('articulo4', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo4', to='articulos.articulo', verbose_name='articulo4')),
                ('articulo5', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo5', to='articulos.articulo', verbose_name='articulo5')),
                ('articulo6', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo6', to='articulos.articulo', verbose_name='articulo6')),
                ('articulo7', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo7', to='articulos.articulo', verbose_name='articulo7')),
                ('articulo8', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo8', to='articulos.articulo', verbose_name='articulo8')),
                ('articulo9', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articulo9', to='articulos.articulo', verbose_name='articulo9')),
            ],
        ),
    ]
