# Generated by Django 4.1.6 on 2023-05-05 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='avatar',
        ),
    ]
