# Generated by Django 4.1.4 on 2023-05-07 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Carrito',
        ),
    ]
