# Generated by Django 4.1.4 on 2023-05-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('usuarios', '0002_remove_cliente_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Carrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito', verbose_name='Carrito'),
        ),
    ]
